# Site settings
title: Michael Cooney
email: mike.cooney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Michael Cooney.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mkcny.com" # the base hostname & protocol for your site
twitter_username: mkcny
github_username:  mkcny

# Build settings
markdown: kramdown
